### ISSUE TITLE
Descriptive namespace

### ISSUE THREAD

**Issue by discospiff** [dhruv0002/IS7024001Project#11]
Consider using a descriptive namespace.  Since QuickType is the default, it may clash after you have more than one client.

https://github.com/dhruv0002/IS7024001Project/blob/043ccc3820eb7b13ca14c6ea08a17c37c91ac40c/Project/Project/Models/Country.cs#L9

**Comment by dhruv0002** [comment]
Hi Professor,
I have resolved this issue. 

Please refer to the commit: https://github.com/dhruv0002/IS7024001Project/commit/556beaa922f258254465b18dcea57297c5abe583

Thanks,
Dhruv Agarwal
