### ISSUE TITLE
Remove redundant title

### ISSUE THREAD

**Issue by discospiff** [dhruv0002/IS7024001Project#12]
Remove "Page" from the name of this page.  That's redundant.

https://github.com/dhruv0002/IS7024001Project/blob/043ccc3820eb7b13ca14c6ea08a17c37c91ac40c/Project/Project/Pages/BreweriesPage.cshtml#L2

**Comment by dhruv0002** [comment]
Hi Professor,
I have resolved this issue.

Please refer to the commit: https://github.com/dhruv0002/IS7024001Project/commit/fbf8a6a04524688828557d9cbfa126e5f65eefef

Thanks,
Dhruv Agarwal
